
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/dbw

  app:
    build: .
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=webrtc_demo
      - PORT=4055
    ports:
      - "4055:4055"
    depends_on:
      - mongo

volumes:
  mongo_data:
