
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/dbw

  app:
    build: .
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27018
      - DB_NAME=webrtc_demo
      - PORT=4070
    ports:
      - "4070:4070"
    depends_on:
      - mongo

volumes:
  mongo_data:
