
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=webrtc_demo
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo_data:
